name: Cargo test suite

on: [push, pull_request]

jobs:
  build:
    container: docker://docker:latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test
      
